In [1]:
print("day-3")

day-3


In [2]:
t1 = (1,2,3,40,"ntt",1.1)
print(t1)

(1, 2, 3, 40, 'ntt', 1.1)


In [3]:
print(type(t1))

<class 'tuple'>


In [4]:
#constructor tuple
t2 = tuple(("ntt",1,2,3,4))
print(t2)

('ntt', 1, 2, 3, 4)


In [6]:
t3 = tuple(["ntt",1,2,3,4])
print(t3)
print(type(t3))

('ntt', 1, 2, 3, 4)
<class 'tuple'>


In [16]:
t4 = tuple((15,))
print(t4)
print(type(t4))

(15,)
<class 'tuple'>


In [19]:
t5= tuple("ntt")
print(t5)
print(type(t5))

('ntt',)
<class 'tuple'>


In [21]:
t5= tuple((15))
print(t5)
print(type(t5))

TypeError: 'int' object is not iterable

In [24]:
t6 = tuple((15,))
print(t6)
print(type(t6))

(15,)
<class 'tuple'>


In [27]:
a= (15,)
print(a)
print(type(a))

(15,)
<class 'tuple'>


In [33]:
#accessing the tuple
t7 = (22,33,44,55,66,77)
print(t7[1])
print(t7[-1])
print(t7[2:10])

print(t7[-4:-1:1])

33
77
(44, 55, 66, 77)
(44, 55, 66)


In [34]:
if 77 in t7:
    print("yes")
else:
    print("no")

yes


In [35]:
#update
t7[0]=100

TypeError: 'tuple' object does not support item assignment

In [37]:
t7 = (22,33,44,55,66,77)
t8 = list(t7)
print(t8)
print(type(t8))
t8[0]=100
print(t8)
t7 = tuple(t8)
print(t7)

[22, 33, 44, 55, 66, 77]
<class 'list'>
[100, 33, 44, 55, 66, 77]
(100, 33, 44, 55, 66, 77)


In [39]:
del t7

In [44]:
#iterate
t7 = (22,33,44,55,66,77)

for i in (10,):
  print(i)

10


In [47]:
s = [["akash",25 ,"BE"],["John",22,'BSC'],["smith",21,'MBBS']]
print(s[1])

['John', 22, 'BSC']


In [49]:
d1 = {"name":"akash","age":25,"course":"BE"}
print(d1)
print(type(d1))

{'name': 'akash', 'age': 25, 'course': 'BE'}
<class 'dict'>


In [50]:
print(d1["name"])

akash


In [52]:
d2 = {10:111111,20:222222,30:333333}
print(d2[10])

111111


In [56]:
d3 ={"usn1" : ["akash",25 ,"BE"] , "usn2" :["John",22,'BSC'] , "usn3": ["smith",21,'MBBS']  }

print(len(d3))

3


In [57]:
d4 = dict(name = "John", age = 36, country = "Norway")
print(d4)

{'name': 'John', 'age': 36, 'country': 'Norway'}


In [58]:
x = d4.keys()
print(x)

dict_keys(['name', 'age', 'country'])


In [59]:
y = d4.values()
print(y)

dict_values(['John', 36, 'Norway'])


In [60]:
z = d4.items()
print(z)

dict_items([('name', 'John'), ('age', 36), ('country', 'Norway')])


In [61]:
d4["name"] = "akash"
print(d4)

{'name': 'akash', 'age': 36, 'country': 'Norway'}


In [62]:
d4.update({"name":"clara"})
print(d4)

{'name': 'clara', 'age': 36, 'country': 'Norway'}


In [63]:
d4["qual"]= "BE"
print(d4)

{'name': 'clara', 'age': 36, 'country': 'Norway', 'qual': 'BE'}


In [64]:
d4.pop("qual")
print(d4)

{'name': 'clara', 'age': 36, 'country': 'Norway'}


In [65]:
d4.popitem()
print(d4)

{'name': 'clara', 'age': 36}


In [66]:
del d4['name']
print(d4)

{'age': 36}


In [67]:
del d4

In [68]:
d4 = dict(name = "John", age = 36, country = "Norway")

for i in d4:
  print(d4[i])

John
36
Norway


In [75]:
#NUMPY
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)
int64


In [77]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [78]:
arr2 = np.array([[[1,2,3],[4,5,6]] , [[11,22,33],[44,55,66]]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
<class 'numpy.ndarray'>
3
12
(2, 2, 3)
int64
